spring:
  datasource:
    oss:
      bucket-name: https://s3.cn-north-1.jdcloud-oss.com
      region: cn-north-1
      access-key: ${JD_CLOUD_OSS_ACCESS_KEY:}
      secret-key: ${JD_CLOUD_OSS_SECRET_KEY:}
      endpoint: denny-test
